In [2]:
from sklearn.cluster import KMeans
import numpy as np

In [3]:
X=np.array([[1,2],[1,4],[1,0],[10,2],[10,4],[10,0]])
print(X)

[[ 1  2]
 [ 1  4]
 [ 1  0]
 [10  2]
 [10  4]
 [10  0]]


In [5]:
kmeans=KMeans(n_clusters=2,random_state=0).fit(X)

In [6]:
kmeans.labels_

array([1, 1, 1, 0, 0, 0])

In [7]:
kmeans.predict([[0,0],[12,3]])

array([1, 0])

In [8]:
kmeans.cluster_centers_

array([[10.,  2.],
       [ 1.,  2.]])